spring.application.name=sysinventory
server.port=8080
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# MongoDB - Usa variable de entorno
spring.data.mongodb.uri=${MONGODB_URI}

# Permite que Spring lea las cabeceras X-Forwarded-* (necesario en Render)
server.forward-headers-strategy=native

# Azure OAuth2 - Usa variables de entorno
spring.security.oauth2.client.registration.azure.client-id=${AZURE_CLIENT_ID}
spring.security.oauth2.client.registration.azure.client-secret=${AZURE_CLIENT_SECRET}
spring.security.oauth2.client.registration.azure.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.azure.redirect-uri={baseUrl}/login/oauth2/code/azure
spring.security.oauth2.client.registration.azure.scope=openid,profile,email,offline_access,https://graph.microsoft.com/Files.Read,https://graph.microsoft.com/Sites.Read.All

spring.security.oauth2.client.provider.azure.authorization-uri=https://login.microsoftonline.com/f33bed9f-22bd-4350-b7da-66bd88fc6458/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.azure.token-uri=https://login.microsoftonline.com/f33bed9f-22bd-4350-b7da-66bd88fc6458/oauth2/v2.0/token
spring.security.oauth2.client.provider.azure.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.azure.user-name-attribute=sub
spring.security.oauth2.client.provider.azure.jwk-set-uri=https://login.microsoftonline.com/f33bed9f-22bd-4350-b7da-66bd88fc6458/discovery/v2.0/keys
spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/f33bed9f-22bd-4350-b7da-66bd88fc6458/v2.0

app.base-url=${APP_BASE_URL:http://localhost:8080}

azure.sharepoint-site=spmardiquesa.sharepoint.com,3755ae40-c380-4ea3-b3f0-de7b358755cd,3c6e5d85-5680-4ccc-94e2-53ac3042aa97
azure.file-id=01P5PRORTSEIX2Q4FK2FEKWVKR733T5QNK
azure.sharepoint-embed-url=https://spmardiquesa.sharepoint.com/:x:/r/sites/TI/_layouts/15/WopiFrame.aspx?sourcedoc=%7BA82F2272-AA70-48D1-AB55-51FEF73EC1AA%7D&action=embedview

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG